apiVersion: v2
name: tinode-server
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: mariadb
    condition: mariadb.enabled
    version: 12.2.4
    repository: "oci://registry.arico-b2b.com/neorcloud"
